### PR TITLE
Specify the controller Id when triggering haptic feedback

### LINKED ISSUE #1488: Haptic feedback sent to the controller with the focus
## Configuration

Wolvic version: 1.6.1
Wolvic build ID: 

Hardware: Quest3

## Steps to Reproduce

1. Enable haptic feedback in the Wovic controller settings dialog 
2. Move the right controller's pointer to enter / leave a widget or panel 
3. Check that the haptic feedback is sent to the right controller
4. Move the left controller's pointer to enter / leave a widget or panel
5. Check that the haptic feedback is sent to the right controller
6. Click on any widget using the left controller
7. Move the right controller's pointer to enter / leave a widget or panel 
8. Check that the haptic feedback is sent to the left controller
9. Move the left controller's pointer to enter / leave a widget or panel 
10. Check that the haptic feedback is sent to the left controller

## Current Behavior

The haptic feedback is sent always to the controller which performed the last click

## Expected Behavior

The haptic feedback is sent to the controller that entered / left a widget or panel

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by javifernandez**
We are sending the haptic feedback to the controller that got the focus due to the last click event. This causes that hovering events generated by the other controller still send the haptic feedback to the inactive controller.

This change defines a new argument in the triggerHapticFeedback function to pass the Id associated to the controller that generated the hovering event.

Fixes #1488

### CODE REVIEW

File: app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java [hunk 1]
```diff
@@ -268,7 +268,8 @@ private boolean callOnAudioManager(Consumer<AudioManager> fn) {
         @Override
         public void onGlobalFocusChanged(View oldFocus, View newFocus) {
             Log.d(LOGTAG, "======> OnGlobalFocusChangeListener: old(" + oldFocus + ") new(" + newFocus + ")");
-            triggerHapticFeedback();
+            // TODO: Which controller should we send the haptic feedback to ?
+            triggerHapticFeedback(0);
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java:272]: I think we might not need this at all?

In which cases not covered by the usages in KeyboardWidget is this triggered?

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java [hunk 2]
```diff
@@ -566,7 +566,8 @@ public void onConfigurationChanged(Configuration newConfig) {
     @Override
     public void onPress(int primaryCode) {
         Log.d(LOGTAG, "Keyboard onPress " + primaryCode);
-        mWidgetManager.triggerHapticFeedback();
+        if (mControlHoverDeviceId != -1)
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:569]: Can it be -1 ?

**Review by svillar — COMMENTED** [review]
Looks great. I have a couple of comments though

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java (hunk 2 above)
Comment (javifernandez) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:569]: Umm, if I've understood it correctly, [updateLastDeviceId](https://github.com/Igalia/wolvic/blob/04131b06656a49f871d85d5855d01c0e123e9562/app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java#L165) can set the deviceId to -1 in some case.

File: app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java (hunk 1 above)
Comment (javifernandez) [reply app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java:272]: Not sure, I didn't want to remove the call as part of this change.

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java (hunk 2 above)
Comment (svillar) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:569]: So the part I don't get is why you check the control hover device id. That refers to the control buttons of the keyboard that are shown on the left (closing, moving, etc...)

Comment (javifernandez) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:569]: ah, I know what you mean. I should have used mPopUpHoverDeviceId instead.

Comment (svillar) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:569]: Why? I don't see any difference. I just don't understand why you're using those. They track whenever the hover is over any of those elements of the keyboard

**Review by svillar — APPROVED** [review]
Great!
