### PR TITLE
Back action improvements

### LINKED ISSUE #672: Handtracking: new back action does not work in Oculus if FBHandTrackingAim is not used
This does not happen in any released package. It does only happen by forcing `mSupportsFBHandTrackingAim` to false. In that case the logic does not support well the Oculus case.

I think the current logic is incorrect because it somehow couples the FB hand tracking aim extension with OCULUSVR and that should be fixed.

### LINKED ISSUE #678: Handtracking: ray visible when hands face head
All the configurations that do not use the FB aim extension to compute the aim do show the ray even when the hands are facing head. We should not show it in those cases.

### PR DESCRIPTION
**Pull request by svillar**
This PR brings a couple of improvements to back action
* Adds a workaround for the lack of valid palm pose in PicoOS (Pico was completely broken when disabling the FB aim extension)
* Disables rendering the ray when palms face head in devices not using the FB aim extension
* Adds back action support for configurations not supporting the FB aim extension but taking over the hands tracking whenever they face the head

Fixes #678, fixes #672

### CODE REVIEW

**Comment by svillar** [comment]
This should be tested in as much as platforms as possible. 

Also ideally, do hardcode `mSupportsFBHandTrackingAim` to `false` in the platforms supporting it, like Meta or Pico. It should work even in those cases.

I went through these configurations but I might have committed some mistake, it'd be nice if reviewers could double check that.

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 1]
```diff
@@ -528,6 +528,15 @@ bool shouldConsiderPoseAsValid(const XrPosef& pose) {
 }
 #endif
 
+static XrHandJointEXT GetHandJointIndexForAim() {
```
Comment (javifernandez) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:531]: Why do we need a function for this ? Wouldn't be more appropriate to use  ``` #define``` directives instead ? 

```
#if defined(PICOXR)
  #define XR_JOINT_PALM XR_HAND_JOINT_WRIST_EXT
#else
  #define XR_JOINT_PALM XR_HAND_JOINT_PALM_EXT
#endif
```

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 2]
```diff
@@ -607,31 +616,34 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
...
-#if defined(OCULUSVR)
-        if (IsHandJointPositionValid(XR_HAND_JOINT_PALM_EXT))
-            leftPalmFacesHead = !mHasAimState;
-#else
-        XrHandJointEXT palmJointIndex = XR_HAND_JOINT_PALM_EXT;
-#if defined(PICOXR)
-        // Pico runtime doesn't provide palm joint info, so we use the wrist instead.
-        palmJointIndex = XR_HAND_JOINT_WRIST_EXT;
+    bool palmFacesHead = false;
+    XrHandJointEXT palmJointIndex = GetHandJointIndexForAim();
```
Comment (javifernandez) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:620]: Not sure we need the pañmJointindez, specially if we use the approach I suggested above.

**Review by javifernandez — APPROVED** [review]
My comments are just suggestions and they don't imply changes in the implemented logic, so feel free to ignore them and land the patch as it is.

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 1 above)
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:531]: that's an interesting, I don't really mind

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 2 above)
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:620]: OK

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 3]
```diff
@@ -648,7 +655,7 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
 
     delegate.SetHandJointLocations(mIndex, jointTransforms);
     delegate.SetAimEnabled(mIndex, mHasAimState);
-    delegate.SetLeftHandActionEnabled(mIndex, leftPalmFacesHead);
+    delegate.SetLeftHandActionEnabled(mIndex, palmFacesHead);
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:658]: BTW this is wrong, I should also check that it's the left hand

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 4]
```diff
@@ -664,9 +671,9 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
     }
     delegate.SetPinchFactor(mIndex, pinchFactor);
     delegate.SetButtonState(mIndex, ControllerDelegate::BUTTON_TRIGGER,
-                            device::kImmersiveButtonTrigger, indexPinching && !leftPalmFacesHead,
-                            indexPinching && !leftPalmFacesHead, 1.0);
-    if (leftPalmFacesHead) {
+                            device::kImmersiveButtonTrigger, indexPinching && !palmFacesHead,
+                            indexPinching && !palmFacesHead, 1.0);
+    if (palmFacesHead) {
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:676]: Also this is probably wrong too, I don't think we should set those values when the right hand is facing the head.

**Comment by javifernandez** [comment]
Thanks for applying the suggested changes. 
I've tested the patch in Oculus, Lynx and Sapces runtimes and I've seen no regressions and the behavior of the back action is much better, in terms of stability and reliability. 

If I have to say something, I'd say that the icon appears slightly before it should in the case of the Space runtime. It's doesn't affect usability, since it's valid enough to avoid activating it accidentally, but if we want to fine tuning, we may want to add some specific values of the kPalmHeadThreshold constant for this runtime.

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 4 above)
Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: Oops, right. That's an existing bug I introduced when trying to fix the single hand locking out the trigger button.

Great if you could fix it as part of this PR :sweat_smile:

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 5]
```diff
@@ -608,30 +615,34 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
...
 #endif
-            auto vectorHead = head.MultiplyDirection({0, 0, -1});
-            leftPalmFacesHead = vectorPalm.Dot(vectorHead) > kPalmHeadThreshold;
+                auto vectorHead = head.MultiplyDirection({0, 0, -1});
+                palmFacesHead = vectorPalm.Dot(vectorHead) > kPalmHeadThreshold;
+                mHasAimState = mHasAimState && !palmFacesHead;
+            }
         }
-#endif
+        leftPalmFacesHead = mHandeness == Left && leftPalmFacesHead;
```
Comment (javifernandez) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:645]: Shouldn't this be ```leftPalmFacesHead = mHandeness == Left && palmFacesHead;``` ?

**Review by javifernandez — CHANGES_REQUESTED** [review]

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 5 above)
Comment (elima) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:645]: Maybe grouping parenthesis around the first condition?

**Review by elima — COMMENTED** [review]
Looks good, but I understand you are still iterating some things. So left a couple of comments.

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 5 above)
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:645]: Sure! :) doing things in a rush is an issue

**Comment by svillar** [comment]
> 

Note that this should not affect the way the icon or the back action works. It's just a  matter of showing/hiding the ray when the action is triggered.

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 6]
```diff
@@ -607,31 +616,34 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
...
+        if (mSupportsFBHandTrackingAim) {
+            // With the FB aim extension we stop getting aim state precisely when hands face head.
+            palmFacesHead = !mHasAimState;
+        } else {
+            if (systemTakesOverWhenHandsFacingHead) {
+                palmFacesHead = !mHasAimState;
+            } else {
+                vrb::Matrix palmMatrix = jointTransforms[palmJointIndex];
+                // For the hand we take the Y axis because that corresponds to head's Z axis when
+                // the hand is in upright position facing head (the gesture we want to detect).
```
[the remark this answers is not in the document]
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:633]: Of course :facepalm: I knew something was wrong there...

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 4 above)
Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: > Oops, right. That's an existing bug I introduced when trying to fix the single hand locking out the trigger button.
> 
> Great if you could fix it as part of this PR sweat_smile

Please ignore this comment. There is a bug indeed but is not related with this PR.

Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: I meant that there is indeed an issue, any hand is not able to trigger a click without having a valid aim state. But it is not related with this PR, so please ignore my comments above. Sorry for the noise.

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 5 above)
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: equality comparisons  have precedence over logical operations (even bitwise) so it should work. If it's a matter just of taste well I think this is more clean, but I'll change it if you strongly feel it's preferrable.

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 7]
```diff
@@ -607,31 +616,34 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
...
+    XrHandJointEXT palmJointIndex = GetHandJointIndexForAim();
+    bool systemTakesOverWhenHandsFacingHead = false;
+#if defined(OCULUS)
+    systemTakesOverWhenHandsFacingHead = true;
 #endif
-        if (IsHandJointPositionValid(palmJointIndex)) {
-            vrb::Matrix palmMatrix = jointTransforms[palmJointIndex];
-            // For the hand we take the Y axis because that corresponds to head's Z axis when
-            // the hand is in upright position facing head (the gesture we want to detect).
+    if (IsHandJointPositionValid(palmJointIndex)) {
```
[the remark this answers is not in the document]
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: > Technically the palm joint doesn't need to be valid for Oculus to show the back-nav icon (assuming we forced `mSupportsFBHandTrackingAim` to false). I know it is stretched but I think this change will not add much consistency to the Oculus case.

That's a good point I'll change that?

[the remark this answers is not in the document]
Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: > My point is that I don't see practical any scenario where we disable FB aim extension on Oculus. For example, I just tested the patch forcing `mSupportsFBHandTrackingAim` to false, and I could see the aim state (beam visible) together with the Oculus system's back nav icon. In that state, user would expect to be able to use the nav-back gesture, because the icon is visible, however it does nothing because the aim is still active.

Really? The patch addresses that case too, I see how the ray is not painted in Oculus forcing the FB extension off.

[the remark this answers is not in the document]
Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: > > Technically the palm joint doesn't need to be valid for Oculus to show the back-nav icon (assuming we forced `mSupportsFBHandTrackingAim` to false). I know it is stretched but I think this change will not add much consistency to the Oculus case.
> 
> Note that condition was already present in the current code.

Right.

[the remark this answers is not in the document]
Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: > > My point is that I don't see practical any scenario where we disable FB aim extension on Oculus. For example, I just tested the patch forcing `mSupportsFBHandTrackingAim` to false, and I could see the aim state (beam visible) together with the Oculus system's back nav icon. In that state, user would expect to be able to use the nav-back gesture, because the icon is visible, however it does nothing because the aim is still active.
> 
> Really? The patch addresses that case too, I see how the ray is not painted in Oculus forcing the FB extension off.

Well with some trying I could make it to see both the ray and the oculus back button, and in that case the pinch doesn't do back-nav. Bu it is true that it is unlikely to be a problem since it is a very narrow angle that allows that.

**Review by elima — APPROVED** [review]
Looks good now, thanks! 

Tested on Quest2 and Pico4. Lets merge this!
