### PR TITLE
Fix left hand action button on Lynx

### LINKED ISSUE #839: Missing hamburger icon with the left-hand gesture
## Configuration

Wolvic version:  1.4.1
Wolvic build ID:  98

Hardware:  Lynx R1

## Steps to Reproduce

1. Perform the left-hand gesture for the back-navigation action 
2. 
3.

## Current Behavior

The icon is displayed for a milisecond and in a wrong position

## Expected Behavior

The hamburger icon should be displayed in the correct position (as it happens with the right-hand gesture)

## Possible Solution

It seems that the problem is that our hand mesh mode provides inverted values for the left hand joints. We are applying some corrections to the hand mesh, but we don't do the same to the icon's transform.

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by elima**
When we introduced the generic hand mesh rendering we broke the left hand button action on Lynx. This patch fixes that and also simplifies the workflow of storing and indexing into the joint matrices vector.

The issue is that the skeleton of our left hand model has the order of the joints in reverse order with respect to what the XR_EXT_hand_tracking extension gives. So we had to correct the order of the matrices there. The problem is that we were doing that too early, during assignment and before calculating the left hand action button matrix, which requires indexing the joint matrices to get the thumb and index tips.

Both Oculus and Lynx use the generic mesh rendering code-path, but only Lynx uses the left hand action button (in Oculus it is already provided by the system). Hence the bug went unnoticed until we tested it on Lynx.

Fixes #839

### CODE REVIEW

File: app/src/main/cpp/BrowserWorld.cpp [hunk 1]
```diff
@@ -548,23 +548,22 @@ BrowserWorld::State::UpdateControllers(bool& aRelayoutWidgets) {
     if (controller.modelToggle)
       controller.modelToggle->ToggleAll(controller.mode == ControllerMode::Device);
 
+    // If we are rendering hands using spheres, update the joints' transforms here.
+    if (controller.handJointTransforms.size() > 0) {
```
Comment (javifernandez) [inline app/src/main/cpp/BrowserWorld.cpp:552]: Why we don't need to check for the controller.handMesh now ?

File: app/src/main/cpp/BrowserWorld.cpp [hunk 2]
```diff
@@ -548,23 +548,22 @@ BrowserWorld::State::UpdateControllers(bool& aRelayoutWidgets) {
...
+      assert(controller.handJointTransforms.size() == controller.meshJointTransforms.size());
+      for (int i = 0; i < controller.handJointTransforms.size(); i++)
+        controller.handJointTransforms[i]->SetTransform(controller.meshJointTransforms[i]);
```
Comment (javifernandez) [inline app/src/main/cpp/BrowserWorld.cpp:555]: I don't understand why we are doing this ? If we are rendering the spheres, like the comment above suggest, we are using the mesh's transforms for the handJoint transforms ?

File: app/src/main/cpp/BrowserWorld.cpp [hunk 3]
```diff
@@ -548,23 +548,22 @@ BrowserWorld::State::UpdateControllers(bool& aRelayoutWidgets) {
...
-        // We substract 1 from the index because we removed the palm joint (index 0) to match
-        // the joints in our hand mesh.
-        indexTipMatrix = controller.meshJointTransforms[indexTipIndex - 1];
-        thumbTipMatrix = controller.meshJointTransforms[thumbTipIndex - 1];
-      } else {
-        assert(controller.handJointTransforms.size() > 0);
-        indexTipMatrix = controller.handJointTransforms[indexTipIndex]->GetTransform();
-        thumbTipMatrix = controller.handJointTransforms[thumbTipIndex]->GetTransform();
-      }
+      indexTipMatrix = controller.meshJointTransforms[indexTipIndex];
```
Comment (javifernandez) [inline app/src/main/cpp/BrowserWorld.cpp:564]: Why we are using now the meshJointTransforms in any case ?

**Review by javifernandez — COMMENTED** [review]
The idea of the changes looks good. Moving the indexes inversion to the handModels makes sense. 

I have some doubts that I'd like to clarify before approving the change. though.

File: app/src/main/cpp/BrowserWorld.cpp (hunk 1 above)
Comment (elima) [reply app/src/main/cpp/BrowserWorld.cpp:552]: Before this PR, we were using the `meshJointTransforms` or `handJointTransforms` vectors to store the joint locations coming from the backend, depending on whether it was Oculus/Lynx (generic hand mesh) or Pico/A3 (spheres). That was confusing and more complex for no reason. At the end, both vectors ultimately store a vrb::Matrix.

This PR changes that by storing the joint locations in the Controller::meshJointTransforms (which is a vector of vrb::Matrix too), and then at render time, we just update the matrix of the spheres' vrb::Transform.

That simplifies the code, as you can see below, where we remove the condition of which array to index into to calculate left hand button action. This will also simplify things when we remove the spheres code-path, since we won't need to touch the rest of the code. 

I had this change already planned, as you can see a similar commit in PR#821 for XR_MSFT_hand_tracking_mesh (3rd commit in the series).

File: app/src/main/cpp/BrowserWorld.cpp (hunk 2 above)
Comment (elima) [reply app/src/main/cpp/BrowserWorld.cpp:555]: Note that this is the same we were doing in ControllerContainer::SetHandJointLocations(), but now we just stored the matrices there, and we assign them to the vrb::Transform of the spheres here. It is the same logic as before, but split in two and moved to a different part of the code.

File: app/src/main/cpp/BrowserWorld.cpp (hunk 3 above)
Comment (elima) [reply app/src/main/cpp/BrowserWorld.cpp:564]: For the reasons explained above. It is simpler and less confusing. At the end both vectors were storing the same info. But having it separated was causing problems. The name `meshJointTransforms` is not very representative now, it could be just `jointMatrices` or anything more generic. I plan to change that in a next re-factoring series.

File: app/src/main/cpp/BrowserWorld.cpp (hunk 1 above)
Comment (javifernandez) [reply app/src/main/cpp/BrowserWorld.cpp:552]: I see, wouldn't be better then to get rid of one of the vectors ? it seems that we still use both; if they are going to eventually have the same values, why we need different vectors ?

File: app/src/main/cpp/BrowserWorld.cpp (hunk 2 above)
Comment (javifernandez) [reply app/src/main/cpp/BrowserWorld.cpp:555]: But why we can't simply use the controller.meshJointTransforms instead copying them to the handJointTransforms vector ? This is also related to my previous question about why we need 2 different vectors.

File: app/src/main/cpp/BrowserWorld.cpp (hunk 1 above)
Comment (elima) [reply app/src/main/cpp/BrowserWorld.cpp:552]: `handJointTransforms` is a vector of `vrb::Transform`, which is a node in the vrb scene graph. These nodes apply a transform to their children, which in this case are the vrb::Geometry for the spheres. So we need this vector to support rendering the spheres for Pico and A3 currently.

The vrb::Transform node has a vrb::Matrix member, which is what needs to be set. Previously, we were setting that member directly from the vector coming from the backend. With this PR, we first store the matrices in `meshJointTransforms`, then at render time we assign the matrices to the vrb::Transform.

File: app/src/main/cpp/BrowserWorld.cpp (hunk 2 above)
Comment (elima) [reply app/src/main/cpp/BrowserWorld.cpp:555]: Because `meshJointTransforms` is just a vector of vrb::Matrix. We need a vrb::Transform node to position the spheres in the correct location and orientation.

File: app/src/main/cpp/HandModels.cpp [hunk 4]
```diff
@@ -183,11 +183,28 @@ HandModels::Draw(const vrb::Camera& aCamera, const Controller& aController) {
...
+
+  // The hand model we are currently using for the left hand has the
+  // bind matrices of the joints in reverse order with respect to that
+  // of the XR_EXT_hand_tracking extension, hence we correct it here
+  // before assigning.
+  if (aController.leftHanded) {
+    for (int i = 0; i < jointMatrices.size() / 2; i++) {
+      auto tmp = jointMatrices[i];
+      jointMatrices[i] = jointMatrices[jointMatrices.size() - i - 1];
+      jointMatrices[jointMatrices.size() - i - 1] = tmp;
```
Comment (svillar) [inline app/src/main/cpp/HandModels.cpp:201]: Can't we just do `std::swap(jointMatrices[i], jointMatrices[jointMatrices.size() - i -1])`

**Review by svillar — CHANGES_REQUESTED** [review]
The idea of moving the specifics out of  ControllerContainer seems good. I just have a general comment, how difficult would it be to correct the 3D model?

Looks like a lot of work to do every time we draw just because a 3D model that I guess could be adjusted to our needs.

File: app/src/main/cpp/HandModels.cpp (hunk 4 above)
Comment (elima) [reply app/src/main/cpp/HandModels.cpp:201]: Right, will fix that.

Comment (elima) [reply app/src/main/cpp/HandModels.cpp]: Fixed

**Comment by elima** [comment]
> The idea of moving the specifics out of ControllerContainer seems good. I just have a general comment, how difficult would it be to correct the 3D model?
> 
> Looks like a lot of work to do every time we draw just because a 3D model that I guess could be adjusted to our needs.

**Comment by elima** [comment]
> The idea of moving the specifics out of ControllerContainer seems good. I just have a general comment, how difficult would it be to correct the 3D model?
> 

I think that correcting it in a persistent way would not be very difficult. We could convert it to glTF format (XML), fix it there, and convert it back to GBL. However, since this assets come from Immersive Web repo, I think we should keep them as-is on disk, and apply the correction in memory upon loading.
 
> Looks like a lot of work to do every time we draw just because a 3D model that I guess could be adjusted to our needs.

Well, it is reversing a 25 elements array, so ~12 swaps. We could afford that but I agree is not ideal.

**Review by svillar — APPROVED** [review]
Let's land this. Thanks
