### PR TITLE
Make texture scale changeable by display DPI

### LINKED ISSUE #1078: How to improve sharpness at 0.5 window size
## Hardware
Quest3 v57
Wolvic 1.5.1 from MetaStore.

## Steps to Reproduce
Just any page

## Current Behavior
Display DPI option seems not working?

## Expected Behavior
Match my android Kiwi Browser which I am running on Quest3 and it is sharp as fck in comparison to wolvic.

## Possible Solution
Increase pixel density?

## Context
Interface is not sharp too aside  three dots menu popup

## Error Logs and Stack Traces

```
```

Shouldn't "Display DPI" option change anything? I don't see a difference between 1 and 9999.
I tried changing devPixelsPerPx in about:config but no luck.
Perhaps wolvic itself is running in low resolution?

### PR DESCRIPTION
**Pull request by HollowMan6**
Resolves #1078

### CODE REVIEW

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/TrayWidget.java [hunk 1]
```diff
@@ -509,7 +509,6 @@ protected void initializeWidgetPlacement(WidgetPlacement aPlacement) {
         aPlacement.rotationAxisX = 1.0f;
         aPlacement.rotation = (float)Math.toRadians(-45);
         aPlacement.cylinder = false;
-        aPlacement.textureScale = 1.0f;
```
Comment (HollowMan6) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/TrayWidget.java:512]: We need to figure out how to remove the gaps when textureScale is lower than 1.0f instead of simply fix the textureScale to 1 here https://github.com/MozillaReality/FirefoxReality/pull/790#issuecomment-440792219

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java [hunk 2]
```diff
@@ -251,7 +251,6 @@ protected void initializeWidgetPlacement(WidgetPlacement aPlacement) {
         aPlacement.density = getBrowserDensity();
         aPlacement.visible = true;
         aPlacement.cylinder = true;
-        aPlacement.textureScale = 1.0f;
```
Comment (HollowMan6) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java:254]: We need to fix the pointer when we don't hard-code the textureScale as 1

**Review by HollowMan6 — COMMENTED** [review]
All fixed now

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java (hunk 2 above)
Comment (HollowMan6) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java:254]: Fixed by https://github.com/Igalia/wolvic/pull/1086/files#diff-343d2af88acc48b1395827803aff28623f8942e6b7e87c7ea0598db849149a58R1097-R1100

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/TrayWidget.java (hunk 1 above)
Comment (HollowMan6) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/TrayWidget.java:512]: Fixed by https://github.com/Igalia/wolvic/pull/1086/files#diff-bff0a507df2c8235d7a28517e9aedb6e8b49af6565b9f6873d8e60d2e289cd7bR150
(hacky but works)

**Comment by felipeerias** [comment]
I've been looking at the relationship between display density and display DPI. For example:

- density 1, DPI 100

pico scale dpi 1 100

- density 2, DPI 200

pico scale dpi 2 200

The second option shows the same text at the same size, but it is much clearer and sharper.

I don't know if there is a way to find the right combination of values for each device automatically.

**Comment by HollowMan6** [comment]
> I don't know if there is a way to find the right combination of values for each device automatically.

After we get this PR merged so that changing DPI works, I guess we can of course pre-set the default values of density and dpi for each device by adding a switch case here:
https://github.com/Igalia/wolvic/blob/a0038431930993141532eb03cad3e5b2e1ada1eb/app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java#L88
https://github.com/Igalia/wolvic/blob/a0038431930993141532eb03cad3e5b2e1ada1eb/app/src/common/shared/com/igalia/wolvic/browser/SettingsStore.java#L91

The current default value looks good to me using Meta Quest 2, and unfortunately, I don't have any other devices. We need to fine-tune those values case-by-case and I suggest we do it in a separate PR.

**Comment by felipeerias** [comment]
Yes, I agree that we should do that in a separate PR.

I have opened https://github.com/Igalia/wolvic/issues/1088 to track that investigation.

**Review by felipeerias — APPROVED** [review]
LGTM
