### PR TITLE
[VisionGlass] Restart activity when unplugging the glasses

### LINKED ISSUE #1764: VisionGlass shows a black screen when reconnecitng the USB cable
## Configuration

Wolvic version: 1.8.1
Wolvic build ID: 

Hardware: Vision Glass

## Steps to Reproduce

1. Connect the Vision Glass device to the phone's USB port
2. Accept the "Wired Projection" prompt dialog.
3. Launch Wolvic 
4. Accept the "USB permissions" dialog to grant Wolvic access the Vision Glass device
5. Accept (again) the "Wired Projection" prompt dialog.
6. Disconnect the USB cable from the phone
7. Connect the USB cable to the phone
8. Accept the "Wired Projection" prompt dialog.
9. Accept the "USB permissions" dialog to grant Wolvic access the Vision Glass device
10. Accept (again) the "Wired Projection" prompt dialog.
 

## Current Behavior

A black screen is shown in the display created by the Vision Glass device.

## Expected Behavior

The Wolvic window should be shown in the Vision Glass

## Error Logs and Stack Traces

<details open>

```
25854-26867 VRB                      E  Function: 'StartFrame' not called on render thread.
25854-26867 VRB                      E  Function: 'Draw' not called on render thread.
25854-26867 VRB                      E  Function: 'Draw' not called on render thread.
25854-26867 VRB                      E  Function: 'EndFrame' not called on render thread.
25854-26867 VRB                      E  Function: 'StartFrame' not called on render thread.
25
```

</details>

### PR DESCRIPTION
**Pull request by svillar**
Then the glasses are desconnected the Display of the Presentation is destroyed.  Creating another Presentation is mandatory on reconnecting because the Display would be different. This means the native machinery is no longer valid. The RenderContext is using a different thread than the one that is using the new GLSurfaceView of the new Presentation.

We'd have to recreate the whole BrowserWorld. Unfortunately this means that we'd have to re-run all the application creation Java code because among other things, we create the Widgets there. As this is all very coupled, there is no easy way to do that outside the application creation code flow.

This means that the only way to get Wolvic running on disconnection is basically to restart the activity. The process is a bit slow because we need to initialize everything again but it's safe and we also ensure that the state is saved and recreated before restarting.

Fixes #1764

### CODE REVIEW

File: app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java [hunk 1]
```diff
@@ -789,6 +789,15 @@ public void onDisplayChanged(int displayId) {
                 @Override
                 public void onDisplayRemoved(int displayId) {
                     Log.d(LOGTAG, "display listener: onDisplayRemoved displayId = " + displayId);
+                    // When the display changes due to disconnection we are forced to recreate the presentation.
```
Comment (javifernandez) [inline app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java:792]: We shouldn't do the restart here because the onDisplayRemoved is also called when pausing the activity on the Phone. If you click on the "square" button of the Android toolbar you will see that Wovic is restarted as well, without disconnecting the device.

I'd suggest using the Presentation's internal DisplayListener, which calls to its "onDisplayRemoved" public function, that we can override in our VisionGlassPresentation class. This approach ensures that the display being removed is the one were the VRBRowserActivity is being rendered.

As a matter of fact, I believe we should use the internal DisplayListener for the onDisplayRemove and onDisplayUpdate events, and only handling here the onDisplayAdded event. 

If we still want to do it here, we would need to check the Display flags to ensure the one being removed is the one associated to the Presentation.

**Review by javifernandez — CHANGES_REQUESTED** [review]
I think the idea is good but the implementation is not correct.

File: app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java (hunk 1 above)
Comment (svillar) [reply app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java]: OK, I'll take a look. Good catch

**Review by javifernandez — APPROVED** [review]
This change doesn't solve / minimize the "transition issue" mentioned before, but I guess we must live with it for now. 

I still think it's better to implement this logic in the Presentatin's "onDisplayRemoved()" method. However, it's perhaps better to think about a bigger refactoring and rely more on the Presentation's internal DispayListener.
