### PR TITLE
HVR uses the local space for determining aim's pose

### LINKED ISSUE #1329: Controllers disabled when trying to start a webxr session
## Configuration

Wolvic version: 1.7 
Wolvic build ID: 308 

Hardware: HVR Glasses 

## Steps to Reproduce

1. Load a webxr game (eg, XR dinosaurs)
2. Clink on "View on XR mode"  button
3. 

## Current Behavior

The interstitial screen is shown and there is no way to dismiss it and entering in the WebXR session.

## Expected Behavior

After clicking on any controller's button, the webxr session should be presented.

## Context

This is happening only using the Chromium backend.

After some debugging time I came to the conclusion that there is some problem to use the gripSpace to get the aim's pose. We have a [comment](https://github.com/Igalia/wolvic/blob/9571560885974214263c13d453fbca36fe325e29/app/src/openxr/cpp/OpenXRInputSource.cpp#L756) in the code that Chromium requires the gripSpace when in WebXR sessions, unlike the gecko backend which uses the localSpace as base space.

For some reason the GetPoseSpace call returns a poseLocation with an invalid orientantion bit, so we early return without enabling the controllers. 

Under this situation, we can't click on any button while the interstitial widget is being show and in consequence the webxr session is not started.

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by javifernandez**
The Chromium backend expects the aim's pose to be determined based on the grip space. However, the pose returned by HVR OpenXR runtime has an invalid orientation bit, so our code assume there is no controller available. This problem causes that there is no way of dismissing the interstitial screen an entering the webxr session, as described in the issue #1329. 

This PR tries to workaround the issue by forcing the use of the local space in HVR devices, even that we know Chromium expects to be based on the grip space.

Fixes #1329

### CODE REVIEW

**Comment by svillar** [comment]
If we know that the orientation bit is invalid why don't we change it instead of this change?

**Comment by javifernandez** [comment]
> If we know that the orientation bit is invalid why don't we change it instead of this change?

The position bit is also invalid.

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 1]
```diff
@@ -821,6 +822,16 @@ void OpenXRInputSource::Update(const XrFrameState& frameState, XrSpace localSpac
...
         flags |= device::GripSpacePosition;
         delegate.SetBeamTransform(mIndex, vrb::Matrix::Identity());
+#if defined(CHROMIUM) && defined(HVR)
+        // HVR runtime incorrectly return the same values for grip and aim poses. We circumvent that
+        // by inventing a grip pose. The values are chosen to match the controller dimensions. This
+        // is only needed for Chromium because it requires the grip to be based on the aim. As the
+        // runtime returns invalid values for that case, we need to emulate the aim based on grip.
+        if (renderMode == device::RenderMode::Immersive) {
+            static const auto emulatedGripTransform = vrb::Matrix::Translation({0.0, 0.30, 0.0}).Rotation(vrb::Vector(1.0, 0.0, 0.0), -M_PI / 5);
+            delegate.SetTransform(mIndex, emulatedGripTransform);
```
Comment (javifernandez) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:832]: We have set the delegate's transform to the pointerTransform, built with the "incorrect" baseSpace (the localSpace instead of the expected gripSpace). So now we fix this by assigning an emulated grip transform, but we do so only in the case we have an active grip location.

Additionally, we have a code a few lines above that sets the pointerTransform as the ImmersiveBeamTransform in the case the grip location is not tracking the position. Is this correct ? 

Shouldn't we just fix the pointerTransform before ? and use the emulated one, when needed (eg. HVR buggy runtime) in the rest of the code ?

Comment (svillar) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:832]: Do you mean moving this hack outside the `isPoseActive` check?

**Review by svillar — APPROVED** [review]
Let's merge it
