### PR TITLE
Fix restarting Wolvic

### LINKED ISSUE #949: "RESTART NOW" does not restart
There are some settings in Wolvic that setup the way the web engine works. Those settings are normally passed to the engine on startup, meaning that changing them requires a restart from Wolvic.

When that happens a dialog is shown prompting the user to either restart now or later. By clicking on "RESTART NOW" Wolvic properly closes but is not launched again.

I think this has never really worked, at least I don't remember the last time I got that working.

### PR DESCRIPTION
**Pull request by HollowMan6**
Resolves #949 

Based on the answer from https://stackoverflow.com/a/71392776

This works with Android > 10, tested up to Android 13 (preview).

Someone said that they also tested in Android 7 and it works well.

Since Android 10, you can't launch from the background, so the old method is no longer working:
https://developer.android.com/guide/components/activities/background-starts

The new one no longer needs to schedule a start from the background, so just remove the scheduled way of restarting.

### CODE REVIEW

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/RestartDialogWidget.java [hunk 1]
```diff
@@ -31,7 +31,7 @@ public void updateUI() {
 
             } else if (index == PromptDialogWidget.POSITIVE) {
                 mWidgetManager.saveState();
-                postDelayed(() -> SystemUtils.scheduleRestart(getContext(), 100), 500);
+                postDelayed(() -> SystemUtils.restart(getContext()), 500);
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/RestartDialogWidget.java:34]: Any reason for increasing the delay to half a second?

File: app/src/common/shared/com/igalia/wolvic/utils/SystemUtils.java [hunk 2]
```diff
@@ -35,24 +32,12 @@ public class SystemUtils {
...
-                PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_IMMUTABLE);
-        AlarmManager mgr = (AlarmManager) context.getSystemService(Context.ALARM_SERVICE);
-        mgr.set(AlarmManager.RTC, System.currentTimeMillis() + delay, mPendingIntent);
-
-        System.exit(0);
+    public static void restart(@NonNull Context context) {
+        PackageManager pm = context.getPackageManager();
+        Intent intent = pm.getLaunchIntentForPackage(context.getPackageName());
+        Intent mainIntent = Intent.makeRestartActivityTask(intent.getComponent());
+        context.startActivity(mainIntent);
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/utils/SystemUtils.java:39]: You can even use a single line for these two statements

**Review by svillar — CHANGES_REQUESTED** [review]
Works amazingly well, just some minor comments

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/RestartDialogWidget.java (hunk 1 above)
Comment (HollowMan6) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/RestartDialogWidget.java:34]: It's not increasing the delay. We had a delay of half a second originally.

Comment (svillar) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/dialogs/RestartDialogWidget.java:34]: Oh indeed, I got confused by our scheduled call.

File: app/src/common/shared/com/igalia/wolvic/utils/SystemUtils.java (hunk 2 above)
Comment (HollowMan6) [reply app/src/common/shared/com/igalia/wolvic/utils/SystemUtils.java]: Done!

**Review by svillar — APPROVED** [review]
