### PR TITLE
Make keyboard follow the system locale if never manual select

### LINKED ISSUE #845: Keyboard layout doesn't match the system's language
## Configuration

Wolvic version:  main branch
Wolvic build ID: 

Hardware:  Oculus Quest2

## Steps to Reproduce

1. Launch wolvic
2. Confirm the keyboard layout matches the system's language  
3. Launch the system settings  and change the language 
4. Reboot
5. Launch Wolvic 
6. Type in the url bar

## Current Behavior

The keyboard shows English layout

## Expected Behavior

The keyboard's layout should match the language setting (Spanish)

## Context

This is not happening in 1.4.1 so probably a regression introduced recently.

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by HollowMan6**
Now we don't record the keyboard layout that comes from the system's locale. We only remember the settings if the user has ever chosen a keyboard layout manually.

Resolves #845

### CODE REVIEW

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java [hunk 1]
```diff
@@ -431,12 +431,12 @@ private int getKeyboardWidth(float aAlphabeticWidth) {
         return (int) width;
     }
 
-     private int getKeyboardHeight(float aAlphabeticHeight) {
+    private int getKeyboardHeight(float aAlphabeticHeight) {
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:434]: Good but unrelated, let's keep it out of this patch

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java [hunk 2]
```diff
@@ -431,12 +431,12 @@ private int getKeyboardWidth(float aAlphabeticWidth) {
...
         float height = aAlphabeticHeight;
         height += WidgetPlacement.dpDimension(getContext(), R.dimen.autocompletion_widget_line_height);
         height += WidgetPlacement.dpDimension(getContext(), R.dimen.keyboard_layout_padding);
         return (int) height;
-     }
+    }
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:439]: Ditto

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java [hunk 3]
```diff
@@ -655,7 +655,7 @@ public void onKey(int primaryCode, int[] keyCodes, boolean hasPopup) {
 
     @Override
     public void onNoKey() {
-       hideOverlays();
+        hideOverlays();
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:658]: Ditto

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java [hunk 4]
```diff
@@ -877,7 +877,7 @@ private void handleDomainChange(KeyboardSelectorView.Item aItem) {
         updateCandidates();
     }
 
-    private void handleLanguageChange(KeyboardInterface aKeyboard) {
+    private void handleLanguageChange(KeyboardInterface aKeyboard, boolean remember) {
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java:880]: Adding booleans to a method signature is not generally the best idea because that forces developers to always check the method implementation/docs in order to know what a given `callMethod(true,true,false)` does.

I'd suggest defining and enumerated type with values like Remember::Yes and Remember::No which are much more explicit in the call sites.

**Review by svillar — CHANGES_REQUESTED** [review]
I'm likely not understanding the patch properly but as far as I see with this patch we'll never remember the keyboard set by the user, only the one set in the initialization which I presume is the one selected from the system locale, or am I wrong?

**Comment by HollowMan6** [comment]
> I'm likely not understanding the patch properly but as far as I see with this patch we'll never remember the keyboard set by the user, only the one set in the initialization which I presume is the one selected from the system locale, or am I wrong?

@svillar  The actual situation is in contrast. We will remember the keyboard set by the user. If the user has never set any keyboard, we will follow the one set in the initialization, which is the one selected from the system locale.

**Comment by javifernandez** [comment]
> > I'm likely not understanding the patch properly but as far as I see with this patch we'll never remember the keyboard set by the user, only the one set in the initialization which I presume is the one selected from the system locale, or am I wrong?
> 
> @svillar The actual situation is in contrast. We will remember the keyboard set by the user. If the user has never set any keyboard, we will follow the one set in the initialization, which is the one selected from the system locale.

Where is the code that checks, when handling a locale change, whether the user has previously selected a specific keyboard layout and keep this instead of the one associated to the new locale ?

**Comment by HollowMan6** [comment]
> Where is the code that checks, when handling a locale change, whether the user has previously selected a specific keyboard layout and keep this instead of the one associated to the new locale ?

The logic doesn't work like that. Actually, it works like this:
- We always try to fetch the keyboard layout from the settings store, and apply the layout.
- By default, there's nothing in the settings store, so the keyboard is decided from the system locales, and this PR makes changes as such that we **no longer** remember the decision according to the system locales and we now don't store it in settings.
- When users manually change the keyboard, we will still store it into the settings.

**Review by svillar — APPROVED** [review]
OK I was confused by the ChangeLog message, I was understanding it the other way around, that's why the code was doing the opposite of what I thought you were saying.
