### PR TITLE
Fix several issues related to Download List

### LINKED ISSUE #777: Need to format file sizes consistently
We already use `Formatter.formatFileSize()` in the download and upload dialogs.

However, we are still using a different implementation in the Downloads list, in the method `Download.progressString()`. We should replace that custom implementation with the system's default, so file sizes are displayed consistently everywhere in the application.

### PR DESCRIPTION
**Pull request by HollowMan6**
- Change the download folder into the public as it looks totally fine to do so in Meta Quest 2.
- Get rid of all the nasty code we have to copy files from Wolvic's storage data to system's as there's no need for that any more.
- Fix blob download notification, so that it can be shown as well.
- Fix the download filename when it contains '-' and we download again. e.g.: If the filename is my-download.png, when download again the filename will be m-1.png. This PR fixes it so that it can be my-download-1.png
- Fix #777, replace that custom implementation with the system's default (Formatter.formatFileSize()), so file sizes are displayed consistently everywhere in the application.

### CODE REVIEW

File: app/src/common/shared/com/igalia/wolvic/downloads/DownloadsManager.java [hunk 1]
```diff
@@ -322,6 +314,21 @@ private void notifyDownloadsUpdate() {
         }
     }
 
+    private void notifyDownloadCompleted(@NonNull long downloadId) {
+        if (mDownloadManager != null) {
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/downloads/DownloadsManager.java:318]: Let's early return if `== null` and then we could save an indentation level

**Review by svillar — CHANGES_REQUESTED** [review]
Awesome, I just have a minor nit

**Review by svillar — APPROVED** [review]
This is so cool
