### PR TITLE
Use the the system's DeviceType for the generic input profile

### LINKED ISSUE #833: No hand interaction at all in the Moonrider game
## Configuration

Wolvic version: 1.4.1
Wolvic build ID: 98

Hardware: Lynx R1

## Steps to Reproduce

1. Load the moonrider game
2.
3.

## Current Behavior

No controllers are visible in when the game is running

## Expected Behavior

Wolvic should render emulated controllers to interact with the game.

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by javifernandez**
The generic input profile is associated to the device::UnknownType which uses an empty VR controller in mozilla. The consequence is that there no controller is drawn during WebXR experiences for devices using the generic profile (eg Lynx). 

This issue had been fixed already in PR #834, but it got reverted because it broke the logic to detect generic profiles as fallbacks (see PR #907)

The solution proposed in this PR is to assign the DeviceType provided by the system to the ControllerDelegate instance, instead of the one provided by the generic profile.

Fixes #833

### CODE REVIEW

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 1]
```diff
@@ -701,7 +701,10 @@ void OpenXRInputSource::Update(const XrFrameState& frameState, XrSpace localSpac
 
     delegate.SetLeftHanded(mIndex, mHandeness == OpenXRHandFlags::Left);
     delegate.SetTargetRayMode(mIndex, device::TargetRayMode::TrackedPointer);
-    delegate.SetControllerType(mIndex, mActiveMapping->controllerType);
+    if (mActiveMapping->controllerType == device::UnknownType)
+        delegate.SetControllerType(mIndex, DeviceUtils::GetDeviceTypeFromSystem(false));
+    else
+        delegate.SetControllerType(mIndex, mActiveMapping->controllerType);
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:707]: I prefer this to happen in `OpenXRInputSource::Initialize()`. We can directly modify the mapping that is added to the `mMappings` vector.

**Review by svillar — CHANGES_REQUESTED** [review]

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 1 above)
Comment (javifernandez) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: Sure, done.

File: app/src/main/cpp/ExternalVR.cpp [hunk 2]
```diff
@@ -262,6 +262,7 @@ mozilla::gfx::VRControllerType GetVRControllerTypeByDevice(device::DeviceType aT
     case device::UnknownType:
     default:
       result = mozilla::gfx::VRControllerType::_empty;
+      assert(!"Unknown controller type.");
```
Comment (svillar) [inline app/src/main/cpp/ExternalVR.cpp:265]: What is that ! for?

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 3]
```diff
@@ -73,7 +73,10 @@ XrResult OpenXRInputSource::Initialize()
     for (auto& mapping: OpenXRInputMappings) {
       // Always populate default/fall-back profiles
       if (mapping.controllerType == device::UnknownType) {
-        mMappings.push_back(mapping);
+          // Use the system's deviceType instead to ensure we get a valid VRController on WebXR sessions
+          auto systemMapping = mapping;
+          systemMapping.controllerType = deviceType;
+          mMappings.push_back(systemMapping);
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:79]: why not just
```
mmappings.push_back(mapping)
mmappings.back().controllerType = deviceType
 ```

**Review by svillar — CHANGES_REQUESTED** [review]
Almost there

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 3 above)
Comment (javifernandez) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:79]: Indeed !

File: app/src/main/cpp/ExternalVR.cpp (hunk 2 above)
Comment (javifernandez) [reply app/src/main/cpp/ExternalVR.cpp:265]: It's like ```assert (false)``` , kind of an alternative for ```assert_notreached``` , but it shows the "string" in the backtrace:

```
2023-09-29 16:51:46.120  3901-3983  libc                    com.igalia.wolvic.dev                A  /home/javi/devel/Wolvic/wolvic/app/src/main/cpp/ExternalVR.cpp:265: mozilla::gfx::VRControllerType crow::GetVRControllerTypeByDevice(device::DeviceType): assertion "!"Unknown controller type."" failed
```

**Review by svillar — APPROVED** [review]
Thanks!

File: app/src/main/cpp/ExternalVR.cpp (hunk 2 above)
Comment (tiagovignatti) [reply app/src/main/cpp/ExternalVR.cpp:265]: The assert added here raises SIGABRT when using Wolvic with `noapi`. Before that, I was able to start immersive sessions and use it for basic debugging with `noapi`, even without proper input controller was getting assigned on such configuration.
