### PR TITLE
Disable the XR_EXT_hand_interaction extension in Pico

### LINKED ISSUE #1528: V1.7 broken on Pico
## Configuration

 

Wolvic version: 1.7.0
Wolvic build ID: pico

Hardware: pico 4

## Steps to Reproduce

1. Update Wolvic to latest version from Pico store
2. Launch wolvic
3. Try to use the controllers - you can't, they're frozen in mud air and don't respond.

## Current Behavior
 controllers not recognised/functioning

 
## Expected Behavior
 controllers should function normally

## Possible Solution
 roll back Pico version in the store or fix the problem and republish v1.7

## Context

 cannot use Wolvic at all on Pico 4

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by javifernandez**
It seems that the XR_EXT_hand_interaction is supported in Pico since the OS version 5.11.0, However, due to some bugs
in the OpenXR runtime, it prevents the controller's input profile to be used.

Fixes #1528

### CODE REVIEW

File: app/src/openxr/cpp/OpenXRExtensions.cpp [hunk 1]
```diff
@@ -47,6 +47,7 @@ void OpenXRExtensions::Initialize() {
 #elif PICOXR
     // Pico incorrectly advertises this extension as supported but it makes Wolvic not work.
     sSupportedExtensions.erase(XR_EXTX_OVERLAY_EXTENSION_NAME);
+    sSupportedExtensions.erase(XR_EXT_HAND_INTERACTION_EXTENSION_NAME);
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRExtensions.cpp:50]: Add a comment explaining that 5.11 added it but that there is a bug in the runtime that prevents other interaction profiles from being used (like the ones for controllers) if that is active

**Review by svillar — CHANGES_REQUESTED** [review]
The ChangeLog should change, the issue is in Pico runtime, it isn't a Wolvic's fault after all

File: app/src/openxr/cpp/OpenXRExtensions.cpp (hunk 1 above)
Comment (javifernandez) [reply app/src/openxr/cpp/OpenXRExtensions.cpp:51]: Done

**Review by svillar — APPROVED** [review]
