### PR TITLE
Fixes related to URL schemes

### LINKED ISSUE #1391: Add support for typing data URLs
The engines used by Wolvic obviously support data URLs. However if we type an URL in the URL bar the browser will try to search the text as it won't be recognized as a valid URL by Wolvic

### PR DESCRIPTION
**Pull request by svillar**
We didn't have support for `chrome://` pages because it was not recognized as a scheme handled by the engine. That's correct for Gecko but not for Chromium. So we had to refactor some UrlUtils to cope with engine differences. This also fixes a hidden bug handling the launch of externally managed URLs via intents.

Fixes #1391

### CODE REVIEW

File: app/src/common/gecko/com/igalia/wolvic/browser/api/impl/SessionImpl.java [hunk 1]
```diff
@@ -409,4 +412,17 @@ private int toGeckoFlags(@LoadFlags int flags) {
         }
         return result;
     }
+
+    @Override
+    public UrlUtilsVisitor getUrlUtilsVisitor() {
+        if (mUrlUtilsVisitor == null) {
+            mUrlUtilsVisitor = new UrlUtilsVisitor() {
+                private final List<String> ENGINE_SUPPORTED_SCHEMES = Arrays.asList("about", "data", "file", "ftp", "http", "https", "moz-extension", "moz-safe-about", "resource", "view-source", "ws", "wss", "blob");                @Override
```
Comment (javifernandez) [inline app/src/common/gecko/com/igalia/wolvic/browser/api/impl/SessionImpl.java:420]: This ```@override``` should be in the next line.

File: app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java [hunk 2]
```diff
@@ -472,4 +475,19 @@ public void onLoginUsed(@NonNull PasswordForm form) {
     public WResult<Boolean> checkLoginIfAlreadySaved(PasswordForm form) {
        return mRuntime.getUpLoginPersistence().checkLoginIfAlreadySaved(form);
     }
+
+    @NonNull
+    @Override
+    public UrlUtilsVisitor getUrlUtilsVisitor() {
+        if (mUrlUtilsVisitor == null) {
```
Comment (javifernandez) [inline app/src/common/chromium/com/igalia/wolvic/browser/api/impl/SessionImpl.java:482]: Nit: I assume the most likely case is going to be mUrlUtilsVisitor != null, hence perhaps it would be better to early return in that case. What do you think ?

File: app/src/common/gecko/com/igalia/wolvic/browser/api/impl/SessionImpl.java [hunk 3]
```diff
@@ -409,4 +412,17 @@ private int toGeckoFlags(@LoadFlags int flags) {
         }
         return result;
     }
+
+    @Override
+    public UrlUtilsVisitor getUrlUtilsVisitor() {
+        if (mUrlUtilsVisitor == null) {
```
Comment (javifernandez) [inline app/src/common/gecko/com/igalia/wolvic/browser/api/impl/SessionImpl.java:418]: Ditto

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java [hunk 4]
```diff
@@ -2229,9 +2231,14 @@ public void onDrmStateChanged(Session aSession, @SessionState.DrmState int aDrmS
 
     @Override
     public boolean onHandleExternalRequest(@NonNull String url) {
-        if (UrlUtils.isEngineSupportedScheme(url)) {
```
Comment (javifernandez) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java:2232]: The isEngineSupportedScheme is already parsing the url. Aren't we duplicating this task now ?

File: app/src/common/shared/com/igalia/wolvic/utils/UrlUtils.java [hunk 5]
```diff
@@ -252,14 +251,12 @@ public static URI parseUri(String aUri) throws URISyntaxException {
...
-    public static String urlForText(@NonNull Context context, @NonNull String text) {
+    public static String urlForText(@NonNull Context context, @NonNull String text, @NonNull WSession.UrlUtilsVisitor visitor) {
         String url = text.trim();
         if ((UrlUtils.isDomain(text) || UrlUtils.isIPUri(text)) && !text.contains(" ")) {
             url = text;
             TelemetryService.urlBarEvent(true);
-        } else if (text.startsWith("about:") || text.startsWith("resource://") || UrlUtils.isFileUri(text)) {
-            url = text;
-        } else {
+        } else if (!isEngineSupportedScheme(url, visitor)) {
```
Comment (javifernandez) [inline app/src/common/shared/com/igalia/wolvic/utils/UrlUtils.java:259]: I think the code would be clearer if we make this clause the first one,

**Review by javifernandez — CHANGES_REQUESTED** [review]

**Comment by svillar** [comment]
After the review I decided to improve the patch and extend it. I'm also adding new unit tests now that the machinery is there.

File: app/src/common/shared/com/igalia/wolvic/utils/UrlUtils.java [hunk 6]
```diff
@@ -254,31 +250,39 @@ public static URI parseUri(String aUri) throws URISyntaxException {
...
+            }
+            // This catches the special case of passing an URL with an invalid IP address
+            if (uri.getHost() == null && uri.getAuthority() != null)
+                return searchURLForText(context, url);
+        } catch (URISyntaxException e) {
+            return searchURLForText(context, url);
+        }
 
-            // Doing search in the URL bar, so sending "aIsURL: false" to telemetry.
+        if (!isEngineSupportedScheme(uri, visitor)) {
```
Comment (javifernandez) [inline app/src/common/shared/com/igalia/wolvic/utils/UrlUtils.java:274]: If we do the scheme check first we may avoid parsing the URL.
