### PR TITLE
Fix OpenXR crash on Pico v5.4.0

### LINKED ISSUE #506: Pico 4 not work since update to 5.4.0
Browser 1.3.1 not work on Pico 4 since update Pico 4 to 5.4.0

### PR DESCRIPTION
**Pull request by felipeerias**
Version 5.4.0 of Pico fixes a bug in the previous versions, but now our workaround for that bug is causing the app to crash on startup.

Additionally, v5.4.0 changed the system name from "Pico: PICO HMD" to "PICO 4", which broke the controller mappings.

Fixes #506

### CODE REVIEW

File: app/src/openxr/cpp/OpenXRLayers.h [hunk 1]
```diff
@@ -183,12 +183,7 @@ class OpenXRLayerBase : public OpenXRLayer {
     XrSwapchainCreateInfo info{XR_TYPE_SWAPCHAIN_CREATE_INFO};
     info.width = width;
     info.height = height;
-    bool shouldZeroInitialize = aSurfaceType == VRLayerSurface::SurfaceType::AndroidSurface;
-#if defined(PICOXR)
-    // Circumvent a bug in the pico OpenXR runtime.
-    shouldZeroInitialize = false;
-#endif
-    if (shouldZeroInitialize) {
+    if (aSurfaceType == VRLayerSurface::SurfaceType::AndroidSurface) {
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRLayers.h:186]: In the short term we should keep the old behaviour for <5.4. I was told that the way to detect the system version is by
```
char buffer[128] = {0};
__system_property_get("[ro.build.id](http://ro.build.id/)", buffer);
__system_property_get("[ro.system.build.id](http://ro.system.build.id/)", buffer);
```

File: app/src/openxr/cpp/OpenXRInputMappings.h [hunk 2]
```diff
@@ -245,6 +245,20 @@ namespace crow {
...
+            "PICO 4",
+            Pico4.systemDoF,
+            Pico4.leftControllerModel,
+            Pico4.rightControllerModel,
+            Pico4.controllerType,
+            Pico4.profiles,
+            Pico4.buttons,
+            Pico4.axes,
+            Pico4.haptics,
+    };
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputMappings.h:261]: I am not sure about this. I think it'd be better to adapt the filtering code. You might add some method that usually returns the string that is in the mapping except that for Pico and version <5.4 it'd return "Pico HMD".

**Review by svillar — CHANGES_REQUESTED** [review]

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 3]
```diff
@@ -58,7 +58,19 @@ XrResult OpenXRInputSource::Initialize()
...
+      // Pico version 5.4.0 changed the system id.
+      if (mapping.controllerType == device::PicoXR) {
+          char buildId[128] = {0};
+          __system_property_get("ro.build.id", buildId);
+          if (!CompareSemanticVersionStrings(buildId, "5.4.0")) {
+              // System version is >= 5.4.0
+              systemFilter = "PICO 4";
+          }
+      }
+#endif
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:72]: Hmm this is not future proof. Note that it'll return "PICO 4" for any device from Pico running 5.4. It might be the Pico4 but also the Pico4E or any other they might ship in the future. I think it'd be much safer to do it in reverse, i.e.
1. replace "Pico HMD" by "PICO 4" in the mappings file
2. if it's <5.4.0 then replace system filter by "Pico HMD". That assumes that any device running <5.4 is a Pico4 which is safer.

**Review by svillar — CHANGES_REQUESTED** [review]

File: app/src/openxr/cpp/OpenXRLayers.h [hunk 4]
```diff
@@ -185,8 +185,13 @@ class OpenXRLayerBase : public OpenXRLayer {
     info.height = height;
     bool shouldZeroInitialize = aSurfaceType == VRLayerSurface::SurfaceType::AndroidSurface;
 #if defined(PICOXR)
-    // Circumvent a bug in the pico OpenXR runtime.
-    shouldZeroInitialize = false;
+    // Circumvent a bug in the pico OpenXR runtime in versions below 5.4.0.
+    char buildId[128] = {0};
+    __system_property_get("ro.build.id", buildId);
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRLayers.h:190]: What about converting this into a function in the new file with utilities that I mentioned in some other comment? Note that this is not Pico specific. I've just found out that you could actually do
```
__system_property_get(ANDROID_OS_BUILD_ID, buildId)
```
as it's defined in `<sys/system_properties.h>`

**Review by svillar — CHANGES_REQUESTED** [review]
Added some more comments.

Now that the patch needs to be reworked a bit, I'd like to ask to split it in two different commits. One for fixing the layers initialization code, and another one for the controllers. Thanks

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 3 above)
Comment (felipeerias) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:72]: Done.

File: app/src/openxr/cpp/OpenXRInputMappings.h (hunk 2 above)
Comment (felipeerias) [reply app/src/openxr/cpp/OpenXRInputMappings.h]: Done.

File: app/src/openxr/cpp/OpenXRLayers.h (hunk 4 above)
Comment (felipeerias) [reply app/src/openxr/cpp/OpenXRLayers.h:190]: Done.

Comment (felipeerias) [reply app/src/openxr/cpp/OpenXRLayers.h]: It doesn't seem that `ANDROID_OS_BUILD_ID` is defined in the public headers. People found out its value by looking at the source code or by using something like `adb shell getprop`.

I have moved the code to get that property to a helper function.

File: app/src/openxr/cpp/OpenXRHelpers.h [hunk 5]
```diff
@@ -148,4 +150,25 @@ inline XrPosef MatrixToXrPose(const vrb::Matrix& aMatrix) {
...
+
+// This function compares two strings containing semantic versions in the MAJOR.MINOR.PATCH format.
+// It will return true if str1 is a lower version than str2, and false if it is the same or higher.
+inline bool CompareSemanticVersionStrings(const std::string& str1, const std::string& str2) {
+    int parsedStr1[3]{}, parsedStr2[3]{};
+    ParseVersionString(str1, parsedStr1, 3);
+    ParseVersionString(str2, parsedStr2, 3);
+    return std::lexicographical_compare(parsedStr1, parsedStr1 + 3, parsedStr2, parsedStr2 + 3);
+}
+
```
[the remark this answers is not in the document]
Comment (felipeerias) [reply app/src/openxr/cpp/OpenXRHelpers.h]: I have created `SystemUtils.h` for this purpose, since we already have `DeviceUtils.h`, JNIUtil.h`, etc.

For now, `SystemUtils.h` contains the functions to handle the system version. We can move more functionality to that file in a different PR.

**Comment by felipeerias** [comment]
@svillar I didn't break up the patch because both issues (layers and controllers) require the same functionality for checking the current Build ID, and both have to be fixed to be able to use the app.

I did move the new utility functions to a separate file.

**Review by svillar — APPROVED** [review]
I'm fine with the fix. Good job
