### PR TITLE
Revamp the computation of controllers' poses

### LINKED ISSUE #1451: XRInputSource.gripSpace gives a different result compared to Meta Quest Browser (resulting in the controllers position being offset from where hey actually should be)
## Configuration

Wolvic version: 315
Wolvic build ID: 77fc64b77 (AC 121.1.0)

Hardware: Meta Quest 2

## Steps to Reproduce
1. go to https://signorpipo.itch.io/pplayground-wonderland-engine
2. enter vr session
3. try to put the controller as close as possible and it will be very clear they are not actually in sync with the real world controller position
4. check on meta quest browser to see the difference

## Current Behavior
The controller position is not in sync with the real position one, while on the quest browser it is

```
```

</details>

### PR DESCRIPTION
**Pull request by svillar**
We used to retrieve both aim and grip poses using the local space as base space. That's problematic because WebXR for example expects the aim to be based on the grip pose instead. The code is now simpler as we don't need to do special things for Chromium. This also allowed us to remove some workarounds like the artificial offsets we had to add to the position of the controllers or correction angles to fix the orientation of some poses.

Also the current code was positioning the controller using the aim when it should really use the grip. We used to do that because there are cases where there is no grip (like when using hands) but for those cases we can always fallback to the aim pose. This fixes the weird orientations shown by controllers when rotating them, they used to rotate around the bottom of the controller instead of using the actual rotation center of the movement.

Another important change is that we now properly separate the computation of controller transform, beam transform and immersive beam transform depending on the rendering mode. The reason for that is clear, WebXR expects all the poses in local space. For the distance to floor it uses the SittingToStandingTransform. For the 2D browsing case however, we need to include the distance to the floor in the poses. Also some of those transforms are useless for some rendering modes, for example WebXR does not need the beam transform, and 2D rendering does not need the immersive beam.Revamp the computation of controllers' poses.

HVR backend is a bit special as it does not compute correctly poses if the base space is not the local space. That forced us to include several ifdefs for the HVR special behaviour.

Last but not least, we had to modify the 3D controller models to remove some extra rotations we had to add in the past to better align the position of the virtual controllers with the position of the real ones.

Fixes #1451, #1832

WIP

### CODE REVIEW

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 1]
```diff
@@ -876,48 +865,74 @@ void OpenXRInputSource::Update(const XrFrameState& frameState, XrSpace localSpac
...
+            beamTransform = origAimTransform;
 #endif
         } else {
-            delegate.SetImmersiveBeamTransform(mIndex, vrb::Matrix::Identity());
+            controllerTransform = gripPositionTracked ? XrPoseToMatrix(gripLocation.pose) : origAimTransform;
+            beamTransform = vrb::Matrix::Identity();
+        }
+        // FIXME: use local-floor space to avoid adding average height manually
+        if (aimPositionTracked || gripPositionTracked) {
+            if (renderMode == device::RenderMode::StandAlone) {
```
Comment (javifernandez) [inline app/src/openxr/cpp/OpenXRInputSource.cpp]: Why we don't need to change the controllerTransform if either aimPositionTracked or gridPositionTracked while in Immersive render mode  ?

Comment (javifernandez) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: Ok, got it. 
I assume the else branch deals with handtracking, which If I understand correctly, we are not touching in this PR. 

Perhaps it's not needed, but I think it'd be useful to see in the code something to distinguish those codedepath. It could be a comment or perhaps a new variable that can be use in the if/then/else block 

```bool isHandTracking = !aimPositionTracked && !gripPositionTracked
   if (isHandTracking) {
     auto hand = mHandeness == OpenXRHandFlags::Left ? ElbowModel::HandEnum::Left :  ElbowModel::HandEnum::Right;
     controllerTransform = elbow->GetTransform(hand, head, controllerTransform); 
   } else {
       // Immersive mode the web engines expect poses in local reference space.
       if (renderMode == device::RenderMode::StandAlone) {
               controllerTransform.TranslateInPlace(kAverageHeight);
       }
   }
