### PR TITLE
Fix Youtube captions

### LINKED ISSUE #717: Youtube Captions
## Configuration

Wolvic version: 1.3.4
Wolvic build ID: 88?
Hardware: Quest 2, V...0659

## Steps to Reproduce
Watch any YouTube video w/ captioning on
## Current Behavior
Subtitles do not show at all
## Expected Behavior
Captions should be visible
## Error Logs and Stack Traces

```
```

</details>

### PR DESCRIPTION
**Pull request by HollowMan6**
We shouldn't add/modify the Youtube timedtext API parameters (for captions), otherwise, it will stop working.

Resolve #717

Simple fix but takes a lot of time when debugging.

### CODE REVIEW

**Comment by HollowMan6** [comment]
Youtube captions API: https://github.com/ivanxuu/getyoutubecc/blob/master/getyoutubecc.py#L34C1-L38

File: app/src/main/assets/extensions/fxr_youtube/background.js [hunk 1]
```diff
@@ -33,6 +33,12 @@ function redirect(details) {
     })
 
     if (found) {
+        // We should not add the app param to the timedtext requests (captions),
+        // otherwise they will fail.
+        if (uri.href.includes("timedtext")) {
```
Comment (svillar) [inline app/src/main/assets/extensions/fxr_youtube/background.js:38]: Nice finding!

I'd check the uri against "http://youtube.com/api/timedtext" tough, seems safer than just checking the existence of timedtext (although I agree should work in 99% of the cases"

Comment (HollowMan6) [reply app/src/main/assets/extensions/fxr_youtube/background.js]: Let's use '.com/api/timedtext?' to match then. The host name can be "https://*.youtube.com/*" and "https://*.youtube-nocookie.com/*", so this should be general enough.

**Review by svillar — APPROVED** [review]
Go!
