### PR TITLE
Set the correct trigger and squeeze button states when hands disappear

### LINKED ISSUE #655: Unable to click using hand tracking if using only one hand
## Configuration

I was only able to reproduce this in Meta Quest2, but I don't see any reason why this could not happen in other devices

## Steps to Reproduce

1. Launch Wolvic with the right controller
2. Leave the controller aside while the splash is shown
3. Browser window is shown and right hand is detected
4. Try to click anywhere

## Current Behavior

Hover and other events work fine, but clicking does not

## Expected Behavior

Clicking should work

## Possible Solution

Looks like it has to do with the fact that we're using just one controller (hand). Somehow the input is locked in the other one. Once both hands are detected it's possible to click again after some time.

### PR DESCRIPTION
**Pull request by elima**
Since we introduce the ability to emulate controllers using the hands, with thumb+index pinch as trigger and thumb+middle pinch as squeeze, we never checked that these hand joints had valid position data, to properly calculate the distance between them.

This is causing that when hands are occluded or completely disappear, the joint data becomes invalid and we may incorrectly detect a pinch gesture. This results in a hand that is not active or visible, could lock the trigger or squeeze buttons in a pressed state, preventing the other hand or the controllers from getting the focus.

This patch makes sure that we detect a pinch gesture when the actual joints have valid positions, and always set the trigger and squeeze button states.

Fixes #655.

### CODE REVIEW

File: app/src/openxr/cpp/OpenXRInputSource.cpp [hunk 1]
```diff
@@ -700,8 +702,12 @@ void OpenXRInputSource::EmulateControllerFromHand(device::RenderMode renderMode,
     delegate.SetCapabilityFlags(mIndex, flags);
 
     // Squeeze action
-    bool middlePinching = GetDistanceBetweenJoints(XR_HAND_JOINT_THUMB_TIP_EXT,
+    bool middlePinching = false;
+    if ((mHandJoints[XR_HAND_JOINT_THUMB_TIP_EXT].locationFlags & XR_SPACE_LOCATION_POSITION_VALID_BIT) != 0 &&
```
Comment (svillar) [inline app/src/openxr/cpp/OpenXRInputSource.cpp:706]: Mind creating a private method that does this check? This will make this if and the above one more understandable.

**Review by svillar — CHANGES_REQUESTED** [review]
Just a minor change before landing

File: app/src/openxr/cpp/OpenXRInputSource.cpp (hunk 1 above)
Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp:706]: Agree, will fix that.

Comment (elima) [reply app/src/openxr/cpp/OpenXRInputSource.cpp]: Fixed

**Review by svillar — APPROVED** [review]
