### PR TITLE
Disable headlock when in VR videos

### LINKED ISSUE #1698: Disable Headlock when starting WebXR/immersive video
## Configuration

Wolvic version: 1.8
Wolvic build ID: 190161443

Hardware: Any

## Steps to Reproduce

1. Search in YouTube for a 3D video (eg Air Pano channel)
2. Go to Wolvic settings and enable headlock
3. Change the window's orientation
4. Enter in immersive move video playing (eg,  activate fullscreen)

## Current Behavior

The Immersive video is broken, since the view is locked to the headset position

## Expected Behavior

Headlock must be disable while playing a 360 video in immersive mode

## Possible Solution

Disable the headlock functionality when starting a new webxr session. This should be done not only for videos, but also for any webexr experience or game.

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by haanhvu**
VR videos are meant for users to be immersed in the whole space around them. Because headlock locks users in the front of them, it needs to be disabled in VR videos. If users enabled headlock before entering VR videos, we disable it when VR videos show and reenable it when they are exited.

Fixes #1698

### CODE REVIEW

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java [hunk 1]
```diff
@@ -99,6 +99,8 @@ public class NavigationBarWidget extends UIWidget implements WSession.Navigation
     private static final int POPUP_NOTIFICATION_ID = 3;
     private static final int WEB_APP_ADDED_NOTIFICATION_ID = 4;
 
+    private static boolean disabledHeadlockForVRVideo;
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java:102]: This must not be static, this is and attribute of the object. Regarding the wording I think I prefer a name describing what we should do, something like shouldRestoreHeadLockOnVRVideoExit.

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java [hunk 2]
```diff
@@ -696,6 +704,9 @@ public void onMediaFullScreen(@NonNull WMediaSession mediaSession, boolean aFull
 
             if (isInVRVideo()) {
                 exitVRVideo();
+                if (disabledHeadlockForVRVideo) {
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java:707]: Looks like not needed because we already do this in exitVRVideo()

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java [hunk 3]
```diff
@@ -681,6 +683,12 @@ public void onMediaFullScreen(@NonNull WMediaSession mediaSession, boolean aFull
             }
 
             if (mAutoSelectedProjection != VIDEO_PROJECTION_NONE && autoEnter.get()) {
+                SettingsStore settingsStore = SettingsStore.getInstance(getContext());
+                if (settingsStore.isHeadLockEnabled()) {
+                    settingsStore.setHeadLockEnabled(false);
+                    disabledHeadlockForVRVideo = true;
+                }
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java:690]: This very same block of code is repeated trice. Let's better move it to a private method and call it in all these places.

**Review by svillar — CHANGES_REQUESTED** [review]
Thanks for the patch!

It indeed fixes the issue but the patch can be improved. See comments inline

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java [hunk 4]
```diff
@@ -773,6 +778,14 @@ private void enterFullScreenMode() {
         mWidgetManager.pushWorldBrightness(mBrightnessWidget, mBrightnessWidget.getSelectedBrightness());
     }
 
+    private void disableHeadlockForVRVideo() {
+        SettingsStore settingsStore = SettingsStore.getInstance(getContext());
+        if (settingsStore.isHeadLockEnabled()) {
+            settingsStore.setHeadLockEnabled(false);
+            shouldRestoreHeadLockOnVRVideoExit = true;
+        }
+    }
```
Comment (svillar) [inline app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java:787]: We can do it better. The way this is implemented is a bit risky because adding a new call to `enterVRVideo` will force us to add also a call to disable headlock, and it's very likely that we could forget about that in some months. So the same way we restore headlock in `exitVRVideo` we can get rid of this new private method and all the code to the end of `enterVRVideo`. This way we'll we safe against future calls.

**Review by svillar — CHANGES_REQUESTED** [review]
Almost ready. I think we can make it even better. Comments inline

File: app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java (hunk 4 above)
Comment (haanhvu) [reply app/src/common/shared/com/igalia/wolvic/ui/widgets/NavigationBarWidget.java:784]: `enterVRVideo` calls `showVRVideo`, and in some places we use `showVRVideo` too. So I put this at the end of `showVRVideo`.

**Review by svillar — APPROVED** [review]
Nice! Thanks for working on this!
