### PR TITLE
Make passthrough work on release builds in Meta devices

### LINKED ISSUE #703: Passsthrough shows a black opaque background
## Configuration

Wolvic version:  1.4
Wolvic build ID:  91

Hardware: Quest2

## Steps to Reproduce

1. Activate the options menu in bottom right corner
2. Switch the passthrough mode on
3.

## Current Behavior

Wolvic is rendered with a background opaque background

## Expected Behavior

There should be a transparent background

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by svillar**
Passthrough support was added to meta some time ago using a FB extension. That extension required the creation of a XrCompositionLayerPassthroughFB that was passed to the compositor. That was working for debug builds but not for release ones. The reason why is because we were storing that object in a local variable that was freed after exiting its scope. It was not enough adding them to a vector because we're using a typecast for the compositor layer generic header.

Instead we now store that composition layer in the OpenXRLayerPassthrough. That requires us to implement the Update() method to initialize it properly before passing it to the compositor. That makes our passthrough layer identical to the other ones (as we were not using/overriding Update()).

Fixes #703

### CODE REVIEW

**Review by elima — APPROVED** [review]
The `isValid()` helper seems unrelated with the problem being fixed, other than that looks good. Feel free to merge as-is, once is tested (I can't test it right now, will do it tomorrow).

File: app/src/openxr/cpp/DeviceDelegateOpenXR.cpp [hunk 1]
```diff
@@ -1105,13 +1103,8 @@ DeviceDelegateOpenXR::EndFrame(const FrameEndMode aEndMode) {
...
       if (m.passthroughLayer && m.passthroughLayer->IsDrawRequested() && m.IsPassthroughLayerReady()) {
-          XrCompositionLayerPassthroughFB passthroughCompLayer = {
-                  .type = XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB,
-                  .flags = XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT,
-                  .space = XR_NULL_HANDLE,
-                  .layerHandle = m.passthroughLayer->xrLayer,
-          };
-          layers.push_back(reinterpret_cast<XrCompositionLayerBaseHeader*>(&passthroughCompLayer));
+          m.passthroughLayer->Update(m.localSpace, predictedPose, XR_NULL_HANDLE);
+          layers.push_back(reinterpret_cast<XrCompositionLayerBaseHeader*>(&m.passthroughLayer->xrCompositionLayer));
```
Comment (javifernandez) [inline app/src/openxr/cpp/DeviceDelegateOpenXR.cpp:1107]: Now that the xrCompositionLayer is own by the OpenXRLayerPassthough class, shouldn't we do a copy here instead of using a reference ? 

I'm worried about use-after-free when the layers vector is destroyed. It seems that the OpenXRLayerPassthough class just destroys the handle directly, and that would be probably enough since the .space pointer is always NULL in our case. Just wanted to double check with you that we are safe with this new approach of making the XrCompositionLayerPassthroughFB memory to be managed in two difference places.

Comment (svillar) [reply app/src/openxr/cpp/DeviceDelegateOpenXR.cpp:1107]: But that won't be a problem because the layers vector does only store const pointers, so nothing will be freed upon destruction.

Comment (javifernandez) [reply app/src/openxr/cpp/DeviceDelegateOpenXR.cpp:1107]: > But that won't be a problem because the layers vector does only store const pointers, so nothing will be freed upon destruction.

Ok, If I've understand it correctly then, the eviceDelegateOpenXR::DeleteLayer will invoke the OpenXRLayerPassthrough::Destroy(, where the handle will be eventually destroyed, assuming that the vector wont be used anymore after that.

**Review by javifernandez — APPROVED** [review]
