### PR TITLE
Remove the passthrough layer when entering immersive

### LINKED ISSUE #1351: Passthrough layer seems to be persistent
## Steps to Reproduce

1. Activate passthrough
2. Deactivate passthrough (although it looks like it happens as well if you keep it active)
3. Enter a WebXR experience like Moonrider

## Current Behavior
Passthrough layer is still visible

## Expected Behavior
It shouldn't be visible at all

### PR DESCRIPTION
**Pull request by svillar**
Some platforms (like Meta) implement passthrough via an special compositor layer called the passthrough layer. This passthrough layer is only added to the list of layers for the compositor when in non immersive mode. This means that should not visible inside immersive experiences. However that was not true for some experiences like Moonrider.

In order to make it work properly we need to destroy that layer when entering immersive and recreate it (if needed) when getting back to standalone mode.

Fixes #1351

### CODE REVIEW

File: app/src/main/cpp/BrowserWorld.cpp [hunk 1]
```diff
@@ -1163,6 +1163,10 @@ BrowserWorld::StartFrame() {
     if (relayoutWidgets) {
       UpdateVisibleWidgets();
     }
+    if (m.device->IsPassthroughEnabled() && m.device->usesPassthroughCompositorLayer() && !m.layerPassthrough) {
```
Comment (javifernandez) [inline app/src/main/cpp/BrowserWorld.cpp:1166]: Just a suggestion; I find the long conditional clause a bit confusing. Wouldn't be clearer to move it to a keep just m.device->IsPassthroughEnabled(), move the rest to a createPassthoughLayerIfNeeded() method; possibly m.device->usesPassthroughCompositorLayer() would become an assert in that case (is it possible that passthough is enabled but we are not using the compositor layer ?

**Review by javifernandez — APPROVED** [review]
The fix works well and the code looks good. I've just added a suggestion that may improve code readability; it doesn't affect the functionality so feel free to ignore it.
